# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1d4eb3987aa7fb88d011fea72087fe076af1a36dec3eceb7d14ba5221a573daea77418ee9cd062e049ea1953828425b2e3fdf57ec0ae78c5af9289b41e62e32

test:
  secret_key_base: 6fe00831cd9146dd6c5bc5bd78467724a12035a9e60e35ef8e6a327578c71e5b19917b067ac78fbb8d570aebb1bdc0ebff9701a64d130382522fa13a47f9a513

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
